/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/user/{id}": {
    /** Get the user with the given id. */
    get: operations["getUser"];
    put: operations["updateUser"];
    delete: operations["deleteUser"];
  };
  "/user": {
    /** Get all the users */
    get: operations["getUsers"];
    post: operations["createUser"];
  };
}

export interface components {
  schemas: {
    Address: {
      street: string;
      state: string;
      city: string;
      country: string;
    };
    User: {
      id: string;
      firstName: string;
      lastName: string;
      /** Format: date */
      birthDate: string;
      address: components["schemas"]["Address"];
    };
  };
}

export interface operations {
  /** Get the user with the given id. */
  getUser: {
    parameters: {
      path: {
        /** the user id */
        id: string;
      };
    };
    responses: {
      /** the user with id id */
      200: {
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
  };
  deleteUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: unknown;
    };
  };
  /** Get all the users */
  getUsers: {
    responses: {
      /** the users list */
      200: {
        content: {
          "*/*": components["schemas"]["User"][];
        };
      };
    };
  };
  createUser: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
  };
}

export interface external {}
